[package]
name = "stacklover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
tokio = { version = "1.35.1", features = ["rt", "macros"] }
futures = "0.3"
auto_enums = "0.8"
