[package]
name = "stacklover-expand"
edition = "2021"

[dependencies]
stacklover = { path = ".." }

[[bin]]
name = "example1"

[[bin]]
name = "example2"

[[bin]]
name = "example3"

[[bin]]
name = "example4"
