name: CI

on: [push]

env:
  RUST_VERSION: 1.75.0

jobs:
  cargo_fmt:
    runs-on: ubuntu-20.04
    steps:
    - run: rustup default ${RUST_VERSION}
    - run: rustup component add rustfmt
    - uses: actions/checkout@v4
    - run: cargo fmt --all -- --check

  cargo_test:
    strategy:
      matrix:
        runs-on:
          - ubuntu-20.04
          - macOS-11
    runs-on: ${{ matrix.runs-on }}
    steps:
    - run: rustup default ${RUST_VERSION}
    - uses: actions/checkout@v4
    - run: cargo test -- --color=always --nocapture

  # MSRV (minimum supported Rust version)
  cargo_test_msrv:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - run: rustup default 1.63.0
    - run: cargo test -- --color=always --nocapture

  cargo_bench:
    runs-on: ubuntu-20.04
    steps:
      - run: rustup default ${RUST_VERSION}
      - uses: actions/checkout@v4
      - run: cd bench && cargo bench
